version: "3"
services:
  app:
    image: ${IMAGE}:${IMAGE_TAG}
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "8000:8000"

     
    depends_on:
      - postgresql
      
    networks:
      - adev-network

  postgresql:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "test123456"
      command: postgres
    networks:
      - adev-network



networks:
  adev-network:
    external: true



