---
- hosts: workers
  remote_user: ec2-user
  gather_facts: yes
  vars:
      token: "{{ hostvars[groups['masters'][0]]['worker_token']['stdout'] }}"
      master: "{{ hostvars[groups['masters'][0]]['ansible_hostname'] }}"
  tasks:

  - name: Join Swarm Cluster as a Worker
    command: docker swarm join --token {{ token }} {{ master }}:2377
    register: worker

  - name: Show Results
    debug: var=worker.stdout

  - name: Show Errors
    debug: var=worker.stderr